Internal Server Error: /api/test/
Traceback (most recent call last):
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/chats/middleware.py", line 34, in __call__
    user = request.user.username if request.user.is_authenticated else 'AnonymousUser'
                                    ^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'user'
/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
2025-07-27 14:11:22.087575 - User: AnonymousUser - Path: /api/test/
/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
2025-07-27 14:12:21.658442 - User: user - Path: /api/conversations/
Internal Server Error: /api/conversations/
Traceback (most recent call last):
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: chats_conversation.participants_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 27, in perform_create
    conversation = serializer.save()
                   ^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: chats_conversation.participants_id_id
2025-07-27 14:12:25.497751 - User: user - Path: /api/conversations/{id}/messages/
Internal Server Error: /api/conversations/{id}/messages/
Traceback (most recent call last):
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 80, in list
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 55, in get_queryset
    conversation = get_object_or_404(Conversation, id=conversation_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kobey/Documents/PROJECTS/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: conversation_id, created_at, message, participants_id, participants_id_id
2025-07-27 14:12:30.779191 - User: user - Path: /admin/
2025-07-27 14:12:40.095486 - User: user - Path: /
Not Found: /
